#!/usr/bin/env bash
# IM Backend — pass pipeline commands
# Generated by TRITON_IM_DEBUG=1
#
# Copy any command below and run it to reproduce that stage.
# Remove passes from the pipeline to inspect intermediate IR.

TRITON_OPT="/Users/meshtag/TritonPIM/third_party/triton/build/cmake.macosx-12.1-arm64-cpython-3.13/bin/triton-opt"

# ── Stage 1 — TTIR ──
# Module attributes (im.num-banks etc.) are set after this pipeline in Python; ttir.mlir already has them.
# input:  im_debug/ttir_input.mlir
# output: im_debug/ttir.mlir
"$TRITON_OPT" im_debug/ttir_input.mlir \
  -pass-pipeline='builtin.module(inline,triton-rewrite-tensor-descriptor-to-pointer,canonicalize,triton-combine,triton-reorder-broadcast,cse,symbol-dce,triton-loop-unroll)'

# ── Stage 2 — TTGIR ──
# input:  im_debug/ttir.mlir
# output: im_debug/ttgir.mlir
"$TRITON_OPT" im_debug/ttir.mlir \
  -pass-pipeline='builtin.module(convert-triton-to-tritongpu{target=im:hbm-pim num-warps=1 threads-per-warp=16 num-ctas=1},rewrite-im-layout,tritongpu-remove-layout-conversions,tritongpu-reduce-data-duplication,canonicalize,cse)'

# ── Stage 3 — LLVM Dialect ──
# input:  im_debug/ttgir.mlir
# output: im_debug/llvm_dialect.mlir
"$TRITON_OPT" im_debug/ttgir.mlir \
  -pass-pipeline='builtin.module(convert-triton-im-to-llvm,convert-scf-to-cf,convert-index-to-llvm,convert-arith-to-llvm,convert-cf-to-llvm,canonicalize,cse)'
